version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres-tiroconarco
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: TiroConArco
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: